import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  listScreenContent: {
    padding: 12,
    paddingTop: 12,
  },
  sectionTitle1: {
    marginTop: 0,
    marginBottom: 2,
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  emptyText: {
    paddingVertical: 18,
    fontSize: 14,
    color: '#6b7280',
  },
  card: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
    backgroundColor: '#fff',
  },
  cardPressed: {
    opacity: 0.75,
  },
  cardDeleted: {
    opacity: 0.55,
  },
  deletedText: {
    textDecorationLine: 'line-through',
  },
  cardTop: {
    gap: 10,
  },
  name: {
    fontSize: 16,
    fontWeight: '600',
  },
  row2: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  fieldInline: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#eef2f7',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#f9fafb',
    minWidth: 140,
  },
  inlineLabel: {
    fontSize: 12,
    color: '#6b7280',
  },
  inlineValue: {
    fontSize: 16,
    fontWeight: '800',
    color: '#111827',
    marginLeft: 10,
  },
  cardBottom: {
    marginTop: 10,
  },
  hint: {
    fontSize: 12,
    color: '#6b7280',
  },
  restore: {
    color: '#2563eb',
    fontWeight: '800',
  },
  form: {
    paddingBottom: 8,
    marginTop: 4,
  },
  collapseHeader: {
    marginTop: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#dbe4f0',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 13,
    backgroundColor: '#f8fbff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  collapseHeaderPressed: {
    opacity: 0.9,
  },
  collapseHeaderMain: {
    flex: 1,
  },
  collapseSummary: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 18,
    color: '#4b5563',
  },
  collapseToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  collapseToggleText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2563eb',
  },
  collapseChevron: {
    fontSize: 14,
    fontWeight: '800',
    color: '#2563eb',
  },
  formHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 10,
    marginBottom: 10,
  },
  formHeaderText: {
    flex: 1,
  },
  formSubtitle: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 18,
    color: '#6b7280',
  },
  resetButton: {
    borderWidth: 1,
    borderColor: '#dbe4f0',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#fff',
  },
  resetButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2563eb',
  },
  paramCard: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#fff',
    marginBottom: 10,
  },
  paramCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  paramTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
    color: '#111827',
  },
  unitBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: '#eff6ff',
  },
  unitBadgeText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#2563eb',
  },
  paramDescription: {
    marginTop: 8,
    fontSize: 12,
    lineHeight: 18,
    color: '#6b7280',
  },
  inputShell: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#dbe4f0',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 4,
    backgroundColor: '#f9fbff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  inputStrong: {
    flex: 1,
    paddingVertical: 10,
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
  },
  inputUnitText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6b7280',
  },
  quickRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  quickChip: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#fff',
  },
  quickChipActive: {
    borderColor: '#bfdbfe',
    backgroundColor: '#eff6ff',
  },
  quickChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#374151',
  },
  quickChipTextActive: {
    color: '#2563eb',
  },
  input: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 14,
    backgroundColor: '#fff',
  },
  resultCollapseHeader: {
    marginTop: 14,
    borderWidth: 1,
    borderColor: '#dbe4f0',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 13,
    backgroundColor: '#f8fbff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  resultCollapseTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  resultBox: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#dbe4f0',
    borderRadius: 20,
    padding: 14,
    backgroundColor: '#f8fbff',
  },
  resultTitle: {
    fontWeight: '800',
    fontSize: 16,
    color: '#111827',
  },
  resultBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#e8f0ff',
  },
  resultBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2563eb',
  },
  resultGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  resultMetricCard: {
    flex: 1,
    minWidth: 140,
    borderRadius: 16,
    padding: 14,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  resultMetricCardPrimary: {
    borderColor: '#bfdbfe',
    backgroundColor: '#eff6ff',
  },
  resultMetricLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6b7280',
    marginBottom: 8,
  },
  resultMetricValue: {
    fontSize: 24,
    fontWeight: '800',
    color: '#111827',
    lineHeight: 28,
  },
  resultMetricUnit: {
    marginTop: 4,
    fontSize: 13,
    color: '#4b5563',
  },
  resultStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  resultStatChip: {
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  resultStatLabel: {
    fontSize: 11,
    color: '#6b7280',
    marginBottom: 2,
  },
  resultStatValue: {
    fontSize: 14,
    fontWeight: '800',
    color: '#111827',
  },
  resultSubcard: {
    marginTop: 12,
    borderRadius: 16,
    padding: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  resultSubcardTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6b7280',
    marginBottom: 4,
  },
  resultSubcardText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  resultHint: {
    marginTop: 10,
    fontSize: 12,
    lineHeight: 18,
    color: '#6b7280',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  modalCenterWrap: {
    width: '100%',
    paddingHorizontal: 16,
  },
  modalCard: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  modalScrollContent: {
    paddingBottom: 4,
  },
  modalTitle: {
    fontWeight: '800',
    marginBottom: 12,
    fontSize: 17,
    color: '#111827',
  },
  modalActions: {
    marginTop: 16,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  modalBtnSecondary: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#f3f4f6',
  },
  modalBtnSecondaryText: {
    color: '#111827',
    fontWeight: '700',
  },
  modalBtnPrimary: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#2563eb',
  },
  modalBtnPrimaryText: {
    color: '#fff',
    fontWeight: '700',
  },
});
