import { StyleSheet } from 'react-native';

export const optimizationStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f3f7fb',
  },
  content: {
    padding: 16,
    paddingBottom: 120,
    gap: 14,
  },
  hero: {
    backgroundColor: '#111827',
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  badge: {
    alignSelf: 'flex-start',
    backgroundColor: '#16a34a',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    marginBottom: 10,
  },
  badgeText: {
    color: '#ecfdf5',
    fontSize: 12,
    fontWeight: '800',
  },
  title: {
    color: '#f8fafc',
    fontSize: 26,
    fontWeight: '900',
    marginBottom: 6,
  },
  subtitle: {
    color: '#cbd5e1',
    fontSize: 14,
    lineHeight: 20,
  },
  panel: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#0f172a',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  sectionTitle: {
    color: '#0f172a',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 4,
  },
  sectionText: {
    color: '#64748b',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
  },
  segmentRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  segment: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#f8fafc',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  segmentActive: {
    borderColor: '#2563eb',
    backgroundColor: '#eff6ff',
  },
  segmentText: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '700',
  },
  segmentTextActive: {
    color: '#1d4ed8',
  },
  field: {
    marginBottom: 12,
  },
  label: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 6,
  },
  input: {
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#f8fafc',
    paddingHorizontal: 12,
    color: '#0f172a',
    fontSize: 15,
  },
  doubleRow: {
    flexDirection: 'row',
    gap: 10,
  },
  half: {
    flex: 1,
  },
  button: {
    minHeight: 50,
    borderRadius: 16,
    backgroundColor: '#2563eb',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
  },
  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  statCard: {
    flexGrow: 1,
    flexBasis: '46%',
    borderRadius: 18,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 12,
  },
  statValue: {
    color: '#0f172a',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 4,
  },
  statLabel: {
    color: '#64748b',
    fontSize: 12,
    lineHeight: 16,
  },
  solutionCard: {
    borderRadius: 18,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 12,
    marginTop: 10,
  },
  solutionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 8,
  },
  solutionTitle: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '900',
  },
  solutionMeta: {
    color: '#64748b',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  scorePill: {
    backgroundColor: '#dcfce7',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  scorePillText: {
    color: '#166534',
    fontSize: 12,
    fontWeight: '900',
  },
  itemText: {
    color: '#334155',
    fontSize: 13,
    lineHeight: 19,
  },
  muted: {
    color: '#64748b',
    fontSize: 13,
    lineHeight: 18,
  },
  warning: {
    color: '#991b1b',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  explanationBox: {
    borderRadius: 18,
    backgroundColor: '#eff6ff',
    borderWidth: 1,
    borderColor: '#bfdbfe',
    padding: 12,
    marginBottom: 12,
    gap: 5,
  },
  explanationTitle: {
    color: '#1e3a8a',
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '900',
    marginBottom: 2,
  },
  explanationText: {
    color: '#1e40af',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
  },
});
