import { StyleSheet } from 'react-native';

export const importanceStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#f3f7fb' },
  content: { padding: 16, paddingBottom: 120, gap: 14 },
  hero: {
    backgroundColor: '#312e81',
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: '#3730a3',
  },
  badge: {
    alignSelf: 'flex-start',
    backgroundColor: '#ede9fe',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginBottom: 10,
  },
  badgeText: { color: '#4c1d95', fontSize: 12, fontWeight: '900' },
  title: { color: '#f8fafc', fontSize: 25, fontWeight: '900', marginBottom: 6 },
  subtitle: { color: '#ddd6fe', fontSize: 14, lineHeight: 20 },
  panel: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#0f172a',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  sectionTitle: { color: '#0f172a', fontSize: 18, fontWeight: '900', marginBottom: 4 },
  sectionText: { color: '#64748b', fontSize: 13, lineHeight: 18, marginBottom: 12 },
  button: {
    minHeight: 50,
    borderRadius: 16,
    backgroundColor: '#7c3aed',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  buttonText: { color: '#ffffff', fontSize: 15, fontWeight: '900' },
  rankRow: {
    borderRadius: 16,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 12,
    marginTop: 10,
  },
  rankTitle: { color: '#0f172a', fontSize: 15, fontWeight: '900' },
  rankMeta: { color: '#64748b', fontSize: 13, lineHeight: 18, marginTop: 4 },
  winner: { borderColor: '#a78bfa', backgroundColor: '#f5f3ff' },
  explanation: { color: '#334155', fontSize: 14, lineHeight: 21 },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { borderRadius: 999, backgroundColor: '#f1f5f9', paddingHorizontal: 10, paddingVertical: 7 },
  chipText: { color: '#334155', fontSize: 12, fontWeight: '800' },
  tableText: { color: '#334155', fontSize: 13, lineHeight: 20 },
  muted: { color: '#64748b', fontSize: 13, lineHeight: 18 },
  jsonBox: { borderRadius: 14, backgroundColor: '#0f172a', padding: 12, marginTop: 10 },
  jsonText: { color: '#e2e8f0', fontSize: 11, lineHeight: 16 },
});
