import { StyleSheet } from 'react-native';

import { colors, radius, shadows, spacing } from '../../shared/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  content: { padding: spacing.lg, paddingBottom: 28 },
  hero: {
    backgroundColor: colors.hero,
    borderRadius: radius.lg,
    paddingVertical: 18,
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.md,
  },
  heroTitle: { color: colors.textOnDark, fontSize: 22, fontWeight: '800' },
  heroSubtitle: { color: colors.textOnDarkSoft, marginTop: 4, fontSize: 13, fontWeight: '600' },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    marginBottom: spacing.md,
    ...shadows.card,
  },
  cardTitle: { fontSize: 16, fontWeight: '800', color: colors.text, marginBottom: 10 },
  totalBox: {
    marginTop: 10,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
  },
  totalLabel: { color: colors.text, fontSize: 13, fontWeight: '900', letterSpacing: 0.6 },
  totalValue: { color: colors.text, fontSize: 16, fontWeight: '900' },
  toggle: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  pressed: { opacity: 0.75 },
  toggleText: { color: colors.text, fontSize: 14, fontWeight: '800' },
  toggleArrow: { color: colors.textMuted, fontWeight: '900' },
  sectionLabel: { marginTop: 2, marginBottom: 8, color: colors.textSoft, fontSize: 13, fontWeight: '800' },
  table: {
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surface,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#F7F8FA',
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSoft,
  },
  th: { paddingVertical: 10, paddingHorizontal: 12, fontSize: 12, fontWeight: '900', color: colors.textSoft },
  thRight: { textAlign: 'right' },
  group: { paddingBottom: 8 },
  groupTitle: {
    paddingTop: 10,
    paddingBottom: 6,
    paddingHorizontal: 12,
    color: colors.text,
    fontSize: 13,
    fontWeight: '900',
  },
  tr: {
    flexDirection: 'row',
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F3F6',
  },
  trPressed: { backgroundColor: colors.surfaceMuted },
  td: { paddingVertical: 12, paddingHorizontal: 12, fontSize: 14, fontWeight: '700', color: colors.text },
  tdRight: { textAlign: 'right' },
  subtotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: colors.hero,
  },
  subtotalText: { color: '#E5E7EB', fontSize: 12, fontWeight: '900', letterSpacing: 0.6 },
  subtotalValue: { color: colors.textOnDark, fontSize: 14, fontWeight: '900' },
  mobileList: {
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surface,
  },
  mRow: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F3F6',
    backgroundColor: colors.surface,
  },
  mName: { fontSize: 15, fontWeight: '800', color: colors.text, marginBottom: 8 },
  mBottom: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  mMeta: { fontSize: 13, fontWeight: '700', color: colors.textMuted, flex: 1 },
  mMetaVal: { color: colors.text, fontWeight: '900' },
  mCost: { fontSize: 14, fontWeight: '900', color: colors.text },
  empty: { textAlign: 'center', color: colors.textMuted, fontStyle: 'italic', paddingVertical: 10 },
  assumptionText: {
    color: colors.textSoft,
    fontSize: 14,
    lineHeight: 20,
  },
  insightLead: {
    color: colors.textSoft,
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 10,
  },
  insightList: {
    gap: 10,
  },
  insightItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  insightIcon: {
    marginTop: 1,
  },
  insightTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  insightTitle: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '900',
  },
  insightDescription: {
    color: colors.textSoft,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
    fontWeight: '600',
  },
  markdownBox: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    backgroundColor: '#F7F8FA',
    padding: 12,
  },
  markdownText: {
    color: colors.text,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
  },

  exportActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 10,
    marginBottom: 10,
  },
  exportButton: {
    flexGrow: 1,
    flexBasis: 150,
    minHeight: 46,
    borderRadius: 14,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 11,
    paddingHorizontal: 12,
  },
  exportButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '900',
    textAlign: 'center',
  },
});